branches:
  only:
  - master
language: node_js
node_js:
  - 6
cache:
  directories:
  - node_modules
script: bash ./deploy.sh
env:
  global:
  - COMMIT_AUTHOR_NAME: "travis-ci"
  - COMMIT_AUTHOR_EMAIL: "travis@travis-ci.org"
  - ENCRYPTION_LABEL: "c130f0b4e96a"